
[main]
prompt=   # красивый символ-стрелка (нужен Nerd Font)
lines=10
width=40
terminal=alacritty
run-command=/bin/fuzzel-run.sh {input}
[colors]
# Фон (глубокий тёмный Gruvbox)
background=282828dd
# Основной текст
text=ebdbb2ff
# Подсветка совпадений (голубой Gruvbox)
match=83a598ff
# Фон выбранного элемента (сине-зелёный Gruvbox)
selection=458588ff
# Текст выбранного элемента
selection-text=ffffffff
# Бордер (жёлтый Gruvbox)
